### ISSUE TITLE
[BUG]: Icon on upper right says im walking but im maintaining my speed above 7km/h

### ISSUE THREAD

**Issue by DomRMG** [open-blox/runblox-app#13]
### OS

Android

### Device Model

Realme C11 2021

### Wallet Address

ticket-1326

### NFT ID

ticket-1326

### Discord Ticket Number

1326

### RunBlox App version

1.2.1(65) 

### What happened?

![19288DAE-26CF-4E64-B194-D575B329667A](https://user-images.githubusercontent.com/108987069/178108787-e83e0839-cd13-4f94-96a3-78decd17adcb.png)

I was running at a maintained speed above 7km/h but the icon on the upper right of the app says im just walking. My gps is also good.

**Comment by lucus-blox** [comment]
Please open the map tab, and see the color of your track for a detailed reason.

**Comment by DomRMG** [comment]
![image](https://user-images.githubusercontent.com/108987069/178722000-a4d92557-75a1-4d34-b734-52a3907d9d8a.png)

![image](https://user-images.githubusercontent.com/108987069/178722054-168c14ab-2412-48a1-a517-0fa2dffe2679.png)

Tried running again but still the same emoji

**Comment by DomRMG** [comment]
Saw some users also on the discord server has the same issue as mine, they have running shoe but the emoji is also walking.

**Comment by DomRMG** [comment]
![image](https://user-images.githubusercontent.com/108987069/179024306-658ac2bd-053a-48b7-99bf-208d9a9a50f6.png)

![image](https://user-images.githubusercontent.com/108987069/179024349-ec6ff604-06ca-48ae-9b36-1879589e6325.jpeg)

Still the same emoji
