### ISSUE TITLE
[BUG]: The amount of tokens earned is only half of what other players earn.

### ISSUE THREAD

**Issue by Taniranda** [open-blox/runblox-app#14]
### OS

Android

### Device Model

Docomo  arrows f-41a

### Wallet Address

0x350AB766a295ad1612e911b65AE57E3f3f4FC453

### NFT ID

#11972  #11725

### RunBlox App version

1.2.1(66)

### What happened?

1. At 2022.7.10 
After the upgrade, it is obvious that I am not earning tokens anymore. I used to earn about 16
![Screenshot_20220708-003407_Discord](https://user-images.githubusercontent.com/108919169/178118427-9bc12b1e-6cc0-4650-a203-1fdade8d062b.jpg)
![20220707_220334](https://user-images.githubusercontent.com/108919169/178118429-ba8eba8c-8f3c-41a4-b429-6b05c50d1f97.jpg)
![20220706_224050](https://user-images.githubusercontent.com/108919169/178118430-fb99231e-e5a3-431d-b4ae-e97a698ffb3c.jpg)
![20220704_213755](https://user-images.githubusercontent.com/108919169/178118431-90f3ad1b-99e6-47bd-98e8-0ee8b14ecb7e.jpg)

Rux, but after the upgrade, I earn only about 8.5! I checked with my friends in the community and they said it was abnormally low, so I'm calling them because I think it's a bug. I am attaching before and after pictures. My level is higher than before the upgrade! Stamina is always 100. Stamina is always 100, running speed and route are the same. I've been playing since Android 10 until I bought a new phone, but it's hard when you can't earn money properly.

**Comment by lucus-blox** [comment]
Please open the map tab while you are running, and see if the color of your track matched your speed. If it is blue or red, it mean either you are too slow or too fast.

**Comment by Taniranda** [comment]
Before the upgrade, I was playing at a speed of 5 km - race pace, but today I played at a speed of 10 km running. I was able to earn quite a bit of Rux. I found that I couldn't earn tokens at 5 km speed.
![Screenshot_20220710-213752_RunBlox](https://user-images.githubusercontent.com/108919169/178146024-8ed8fa05-ad81-419f-a9fc-4393d9ca1d62.jpg)

**Comment by lucus-blox** [comment]
> Before the upgrade, I was playing at a speed of 5 km - race pace, but today I played at a speed of 10 km running. I was able to earn quite a bit of Rux. I found that I couldn't earn tokens at 5 km speed. ![Screenshot_20220710-213752_RunBlox](https://user-images.githubusercontent.com/108919169/178146024-8ed8fa05-ad81-419f-a9fc-4393d9ca1d62.jpg)

Then, I think there should be no problem. Just confirm the speed zone before starting to run.
