### ISSUE TITLE
[BUG]: Reward reduced

### ISSUE THREAD

**Issue by discordiaea** [open-blox/runblox-app#15]
### OS

Android

### Device Model

Realmi 8 Pro 8128

### Wallet Address

0xA9F2281f9a5164D4307a4623cAC40B8228AdEccf

### NFT ID

3445

### Discord Ticket Number

1341

### RunBlox App version

Version 1.2.1(66)

### What happened?

Our earning is significantly different from yesterday even if we run more km for less minutes today. Another thing is that we just repaired our shoes before using it and we leveled it up so attack have additional 4 attributes compared to yesterday.
![received_389105279952906](https://user-images.githubusercontent.com/109023332/178141504-ca387340-ad72-4ccb-9b90-93780760a5c8.jpeg)
![received_458879876069731](https://user-images.githubusercontent.com/109023332/178141509-870d6587-d8dd-4e98-93ca-19b3e29f8f94.jpeg)

**Comment by lucus-blox** [comment]
There have not been any updates on the reward mechanism.
Please check the color of your track in the Map tab while you were running.
You might be too fast or too slow.

**Comment by discordiaea** [comment]
Ohh, yah. I think my brother did run yesterday. So, being faster than your speed range will also cause your income to decrease?

**Comment by lucus-blox** [comment]
> Ohh, yah. I think my brother did run yesterday. So, being faster than your speed range will also cause your income to decrease?

Currently, it only depends on what kind of shoes you have, and whether you are in the optimal speed zone or not.
We will implement more interesting features to make the farming more fun, please look forward to them.
