### ISSUE TITLE
[BUG]: Energy refills even when shoes are listed on market

### ISSUE THREAD

**Issue by salem3358** [open-blox/runblox-app#16]
### OS

iOS

### Device Model

Iphone 11 promax

### Wallet Address

0x64917d88E21993C19035913A9Dc4B3B132E0072b

### RunBlox App version

1.2.2.139

### What happened?

Eneger refills even when shoes are listed for sale

**Comment by lucus-blox** [comment]
There is no refilling if you have listed your shoes.

If you have 0 shoes, you can still get the refill to 2 energy pts.
