### ISSUE TITLE
[BUG]: Speed meter showing as 0 Km/h during the entire run

### ISSUE THREAD

**Issue by Estarrecido** [open-blox/runblox-app#17]
### OS

Android

### Device Model

Android 11 RKQ1.211001.001 - Redmi Note 11

### Wallet Address

0xcfc5c8B428ecB00F77c2d706BF7A69c017ce24E5

### NFT ID

#2813

### RunBlox App version

1.2.1(66)

### What happened?

1. At 2022.07.11 08:19 AM EST
2. Simply started a run
3. Went about 2 minutes and checked the screen, it was showing my speed as 0 Km/h
4. Stopped that run earlier thinking that would fix it and started another
5. Finished using my energy, still showing speed as 0 Km/h, but I got some RUX as reward, just not sure if it is what I should get and no way to know if I was in the optimal speed range.
![image](https://user-images.githubusercontent.com/88408440/178274190-607027cd-d9ee-40d3-a735-55f977ad9ff6.png)
![image](https://user-images.githubusercontent.com/88408440/178274237-fee91517-722f-4567-ad2a-11a9bb0e6e5a.png)

**Comment by lucus-blox** [comment]
Please go to the map tab while running to see if you are in the optimal speed zone.

Looks like there is a bug displaying the speed, but your reward is not affected.

We will look into it.
