### ISSUE TITLE
[BUG]: Issue with activation code

### ISSUE THREAD

**Issue by jejedi** [open-blox/runblox-app#6]
### OS

iOS

### Device Model

Iphone 15

### Wallet Address

0x750d3e097169CeabdD7c5efabFa159937031F96B

### NFT ID

5699

### Discord Ticket Number

1113

### RunBlox App version

1.2.2

### What happened?

I made a mistake 
I do a wrong association between my web account and the app account by using gmail instead of apple authentification.

As a consequence I got a gmail account activated with no shoes ( image with trial shoes ) and an inactivated apple account with my shoes.

How can I solve this problem ?
I tried to force pair but no results.

Thanks for your help !

![Web account](https://user-images.githubusercontent.com/44974428/177709339-03400c42-d5e3-481d-86b2-142cb744f0bc.png)
![apple](https://user-images.githubusercontent.com/44974428/177709336-e6a3a5fe-57a1-4c95-a134-b9c3ca05b609.png)
![gmail](https://user-images.githubusercontent.com/44974428/177709338-9f048892-06f9-41c0-9692-d7a720a8ace3.png)

**Comment by susiyaki** [comment]
@lucus-blox 
I think it's better not to post private information to issues of this repository.

**Comment by lucus-blox** [comment]
Hi @jejedi, don't worry, you can bind your email with your wallet anytime, please head to our community for help on binding/unbinding your email with your wallet.

**Comment by lucus-blox** [comment]
Hi @susiyaki 
There are some guidelines if our users do not feel like sharing private information.
I will update the issue template to ask them to open a Discord ticket if such information is required.

<img width="844" alt="image" src="https://user-images.githubusercontent.com/108740477/177715702-d360696f-db61-4e45-815c-acba3a03e3c8.png">

**Comment by susiyaki** [comment]
> There are some guidelines if our users do not feel like sharing private information.
> I will update the issue template to ask them to open a Discord ticket if such information is required.

Sorry! Did not check the template thank you.

Who do you expect to create feature issue?
Can I direct users to write it here?

**Comment by jejedi** [comment]
@lucus-blox 
If I pair to my gmail account, I need to enter a new activation code.
I tried to use the code provided on discord , but it doesnt work.

![image](https://user-images.githubusercontent.com/44974428/177718125-452b84ac-96aa-487a-b16e-b11e169935e0.png)

https://user-images.githubusercontent.com/44974428/177722818-b051b273-d853-4eba-a662-ed2f0ab0cf78.mp4

**Comment by lucus-blox** [comment]
@jejedi I've reactivated your account. Please enjoy and have fun 🏃🏃🏃

**Comment by jejedi** [comment]
@lucus-blox
Thanks you :)
